name: Java CI (CloudFormation SDK app)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'cicc-sdk-demo/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'cicc-sdk-demo/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: |
          cd cicc-sdk-demo
          mvn -B -DskipTests package
          ls -lh target
